--- 
- 
  become: true
  hosts: all
  tasks: 
    - 
      copy: 
        dest: /opt/apache-tomcat-8.5.35/webapps
        src: /webapp/target/webapp.war
      name: "copy jar/war onto tomcat servers"
